Add controllers
thisisaleksander/java-shareit pull request #1
Opened 2023-06-27 15:58 UTC by thisisaleksander

2023-06-27 16:19 UTC, thisisaleksander commented
Привет!)

Я наконец то смог взяться за Практикум. У меня очень много работы, была сессия, написание курсовой и защита. Решил сделать упор на учебе в универе и работе. 
Ты можешь мне помочь пожалуйста и постараться проверять мои проекты побыстрее, чтобы я смог уложиться в дедлай? Мне можно выделить максимум по 3 дня на каждый и проектов. Постараюсь делать максимально качественно.

Очень не хочется вылетать на последнем модуле, так что я готов с утра до утра писать проекты)

2023-06-28 04:07 UTC, krylov-sergey-sergeevich requested changes
Привет

- Текста в исключениях на англ перевести
- Поправить что отписал

2023-06-28 04:07 UTC, krylov-sergey-sergeevich commented on pom.xml
> +			<version>1.7</version>
Для чего эта библиотека? Чем spring-validator не устраивает?

2023-06-28 04:07 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private Date start;
LocalDateTime выглядит как нужная нам дата?

2023-06-28 04:07 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/error/ErrorHandler.java
> +public class ErrorHandler {
рекомендую еще в логи писать как то так log.info("400 {}", e.getMessage(), e);

2023-06-28 04:07 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/exception/ItemDoNotExistsException.java
> +public class ItemDoNotExistsException extends RuntimeException {
Обычно называют ItemNotFountException в таком стиле

2023-06-28 04:07 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +public class ItemService {
@RequiredArgsConstructor

2023-06-28 04:07 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +        if (localId == null) {
а может по умолчанию 0 дать просто сразу чтобы без проверки

2023-06-28 04:07 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/UserController.java
>  @RequestMapping(path = "/users")
@RequiredArgsConstructor

2023-06-28 04:07 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +public class UserService {
@RequiredArgsConstructor

2023-06-28 07:22 UTC, thisisaleksander commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private Date start;
Да, тоже думаю так лучше

2023-06-28 07:22 UTC, thisisaleksander commented on src/main/java/ru/practicum/shareit/error/ErrorHandler.java
> +public class ErrorHandler {
Переписал все логи

2023-06-28 07:23 UTC, thisisaleksander commented on src/main/java/ru/practicum/shareit/item/exception/ItemDoNotExistsException.java
> +public class ItemDoNotExistsException extends RuntimeException {
Да, так лучше выглядит

2023-06-28 07:23 UTC, thisisaleksander commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +        if (localId == null) {
Поправил

2023-06-28 07:29 UTC, thisisaleksander commented on pom.xml
> +			<version>1.7</version>
В начале нашел реализацию проверки почты, там нужно было добавить эту библиотеку. Потом поменял решение и забыл убрать ее

2023-06-28 08:14 UTC, thisisaleksander commented on pom.xml
> +			<version>1.7</version>
Убрал

2023-06-28 08:15 UTC, thisisaleksander commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private Date start;
В ItemRuquest тоже поменял

2023-06-28 08:16 UTC, thisisaleksander commented on src/main/java/ru/practicum/shareit/item/exception/ItemDoNotExistsException.java
> +public class ItemDoNotExistsException extends RuntimeException {
В части с юзером тоже поменял

2023-06-28 08:25 UTC, thisisaleksander commented on src/main/java/ru/practicum/shareit/user/UserController.java
>  @RequestMapping(path = "/users")
Не понимаю что ты хотел сказать в трех комментариях, где написано @requiredargsconstructor. Такие аннотации же по идее не добавляются к контроллерам и сервисам

2023-06-28 09:36 UTC, thisisaleksander commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +public class UserService {
поправил

2023-06-28 09:37 UTC, thisisaleksander commented on src/main/java/ru/practicum/shareit/user/UserController.java
>  @RequestMapping(path = "/users")
дошло, поправил

2023-06-28 09:37 UTC, thisisaleksander commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +public class ItemService {
done

2023-06-29 04:50 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2023-06-29 19:56 UTC, merged