add-bookings
thisisaleksander/java-shareit pull request #2
Opened 2023-06-30 22:54 UTC by thisisaleksander

2023-07-02 21:35 UTC, thisisaleksander commented
Привет!)

Что то задание этого спринта плохо пошло сначала, несколько раз переделывал. Но вроде получилось.

2023-07-03 06:28 UTC, krylov-sergey-sergeevich requested changes
Привет, неплохо, но есть над чем поработать, давай исправим =)

2023-07-03 06:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    long id;
Long

2023-07-03 06:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @Column(name = "start")
start_date

2023-07-03 06:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @Column(name = "finish")
end_date

2023-07-03 06:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
Long

2023-07-03 06:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
Блин года 3 назад у меня было что аннотация на интерфейсе не совсем сработала, сейчас точно срабатывает уверен?

2023-07-03 06:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
И на методах интерфейса

2023-07-03 06:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    List<Booking> getByUserId(long userId, String state) throws ValidationException;
throws ValidationException; это обязательно?

2023-07-03 06:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Booking  booking = bookingRepository.findById(bookingId)
Давай создадим специальное исключение BookingFoundException наследника NotFoundException и сделаем так чтобы каждый раз не повторять текст:
() -> new BookingFoundException (bookingId));

p.s для остальных исключений тоже можно подумать в эту сторону ...

2023-07-03 06:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    public Booking getBookingById(long userId, long bookingId) {
как то код в методе странновато написан как будто можно получше перекомпоновать

2023-07-03 06:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    public Booking getBookingById(long userId, long bookingId) {
возвращение результата должно быть по хорошему в конце, а не бросание исключения

2023-07-03 06:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        throw new ValidationException("Unknown state: UNSUPPORTED_STATUS");
зачем тут если можно было в default в case запихнуть

2023-07-03 06:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    long id;
Long

2023-07-03 06:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            comment.setCreated(LocalDateTime.now());
Давай создадим класс DateUtils и будем создавать объекты времени через него, это позволит унифицировать способ получения времени и если будут правки делать их в 1 месте.

DateUtils.now()

2023-07-03 06:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private void validateUserId(long userId) {
скорее checkExistUserById

2023-07-03 06:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        try {
это выглядит плоховато надо подумать и убрать try catch

2023-07-03 06:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        try {
пусть бросает исключение в чем проблема

2023-07-03 06:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        try {
оно главное Runtime должно быть

2023-07-03 06:28 UTC, krylov-sergey-sergeevich commented on src/main/resources/application.properties
> +DB_CLOSE_ON_EXIT=FALSE
Это для чего?

2023-07-03 06:28 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
> +    unique (email)
рекомендую констрейнты вот так создавать:
CONSTRAINT pk_user PRIMARY KEY (user_id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)

Те давать им имена и делать после всех полей

2023-07-03 06:28 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
> +    unique (id)
CONSTRAINT pk_item PRIMARY KEY (item_id),
  CONSTRAINT FK_ITEM_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (user_id),
  CONSTRAINT UQ_OWNER_ITEM_NAME UNIQUE(owner_id, name)

2023-07-03 06:28 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
> +    constraint items foreign key (item_id) references items(id)
CONSTRAINT pk_comment PRIMARY KEY (comment_id),
  CONSTRAINT FK_COMMENT_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (user_id),
  CONSTRAINT FK_COMMENT_ON_ITEM FOREIGN KEY (item_id) REFERENCES items (item_id)

2023-07-03 06:28 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
> +    constraint fk_booking_to_users foreign key (user_id) references users(id),
CONSTRAINT pk_booking PRIMARY KEY (booking_id),
  CONSTRAINT FK_BOOKING_ON_BOOKER FOREIGN KEY (booker_id) REFERENCES users (user_id),
  CONSTRAINT FK_BOOKING_ON_ITEM FOREIGN KEY (item_id) REFERENCES items (item_id)

2023-07-03 07:22 UTC, thisisaleksander commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private void validateUserId(long userId) {
поправил

2023-07-03 07:30 UTC, thisisaleksander commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    public Booking getBookingById(long userId, long bookingId) {
Переписал метод

2023-07-03 13:18 UTC, thisisaleksander commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    List<Booking> getByUserId(long userId, String state) throws ValidationException;
по идее это нужно указывать чтобы методы из сервиса который имплементирует могли кидать это исключение, поэтому думаю ее нужно оставить

2023-07-03 13:19 UTC, thisisaleksander commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        throw new ValidationException("Unknown state: UNSUPPORTED_STATUS");
да, поправил

2023-07-03 13:22 UTC, thisisaleksander commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        try {
Да, сделал так чтобы просто метод бросал исключение

2023-07-03 13:26 UTC, thisisaleksander commented on src/main/resources/schema.sql
> +    unique (email)
поправил

2023-07-03 13:31 UTC, thisisaleksander commented on src/main/resources/schema.sql
> +    unique (id)
поправил

2023-07-03 13:31 UTC, thisisaleksander commented on src/main/resources/schema.sql
> +    constraint items foreign key (item_id) references items(id)
поправил

2023-07-03 13:31 UTC, thisisaleksander commented on src/main/resources/schema.sql
> +    constraint fk_booking_to_users foreign key (user_id) references users(id),
поправил

2023-07-03 13:34 UTC, thisisaleksander commented on src/main/resources/application.properties
> +DB_CLOSE_ON_EXIT=FALSE
чтобы бд хранилась, это наверное не обязательно, но не вижу чему это может мешать. Если нужно, то можно убрать конечно

2023-07-03 13:35 UTC, thisisaleksander commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
У меня все работает, и на тестах тоже

2023-07-03 13:49 UTC, thisisaleksander commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            comment.setCreated(LocalDateTime.now());
Да, думаю так будет удобнее

2023-07-03 14:35 UTC, thisisaleksander commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Booking  booking = bookingRepository.findById(bookingId)
да, думаю так можно сделать

2023-07-03 14:36 UTC, thisisaleksander commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    long id;
У нас же можно объявлять id ссылочный типом и примитивом. По идее же нужно использовать самый простой вариант, то есть если нам не нужны в работе все фичи с Long, то лучше использовать long. В нашем случае мы работаем сразу с целыми объектами и нам в принципе и не нужно все что умеет ссылочный тип

2023-07-04 07:07 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2023-07-05 22:27 UTC, merged