add-docker
thisisaleksander/java-shareit pull request #4
Opened 2023-07-11 22:23 UTC by thisisaleksander

2023-07-12 18:25 UTC, krylov-sergey-sergeevich requested changes
Привет, почти хорошо, давай поправим мелочи

2023-07-12 18:25 UTC, krylov-sergey-sergeevich commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +		BookingState state = BookingState.from(stateParam)
Повторяется много раз давай внесем в from выброс исключения и будет автоматически так делаться

2023-07-12 18:25 UTC, krylov-sergey-sergeevich commented on gateway/src/main/java/ru/practicum/shareit/request/dto/RequestDto.java
> +public class RequestDto {
Улучшить название класса, сейчас плохоговорящее

2023-07-12 18:25 UTC, krylov-sergey-sergeevich commented on gateway/src/main/java/ru/practicum/shareit/user/UserRequest.java
> +public class UserRequest {
Улучшить название класса, добавить глагол если можно

2023-07-12 20:09 UTC, thisisaleksander commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +		BookingState state = BookingState.from(stateParam)
вынес

2023-07-13 04:47 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2023-07-19 16:04 UTC, merged